--FETCH DEPARTMENTNAME WISE TOP 3 SALARIES
SELECT *FROM (
SELECT 
E.FIRST_NAME,
E.LAST_NAME,
D.DEPARTMENT_NAME,
E.SALARY,
DENSE_RANK() OVER(PARTITION BY D.DEPARTMENT_NAME ORDER BY SALARY DESC) AS DEN
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON (E.DEPARTMENT_ID=D.DEPARTMENT_ID)
) WHERE DEN<=3;

--FETCH DEPARTMENTNAME WISE TOP 3 SALARIES
SELECT *FROM(
SELECT 
E.FIRST_NAME,
E.LAST_NAME,
D.DEPARTMENT_NAME,
E.SALARY,
DENSE_RANK() OVER(PARTITION BY DEPARTMENT_NAME ORDER BY SALARY DESC) AS RNLK
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON (E.DEPARTMENT_ID=D.DEPARTMENT_ID)
ORDER BY SALARY DESC
)WHERE RNLK<4;



--WAQD- DEPARTMENT NAME WISE TOP 1 RD SALARY
SELECT *FROM (
SELECT 
E.FIRST_NAME,
E.LAST_NAME,
D.DEPARTMENT_NAME,
E.SALARY,
DENSE_RANK() OVER(PARTITION BY D.DEPARTMENT_NAME ORDER BY SALARY DESC) AS DEN
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON (E.DEPARTMENT_ID=D.DEPARTMENT_ID)
) WHERE DEN=1;


