SET SERVEROUTPUT ON
DECLARE
CURSOR EMP_TEST
IS
SELECT FIRST_NAME,LAST_NAME,ROUND(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)/12,0) AS EXPER
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 50 ;

FNAME VARCHAR2(20);
LNAME VARCHAR2(20);
EXPER_01 NUMBER ;

BEGIN
OPEN EMP_TEST ;
LOOP
FETCH EMP_TEST INTO FNAME,LNAME,EXPER_01;
DBMS_OUTPUT.PUT_LINE(FNAME||' '||LNAME||' '||EXPER_01);
EXIT WHEN EMP_TEST%NOTFOUND ;
END LOOP;
CLOSE EMP_TEST;
END;




----===========================================================
SET SERVEROUTPUT ON
DECLARE
 CURSOR EMP_TEST
 IS
 SELECT FIRST_NAME,LAST_NAME,
 ROUND(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)/12,2) AS EXPER
 FROM EMPLOYEES
 WHERE DEPARTMENT_ID=50;
 
 EXPER NUMBER;
 FNAME VARCHAR2(20);
 LNAME VARCHAR2(20);
BEGIN
 OPEN EMP_TEST;
 LOOP
  FETCH EMP_TEST INTO FNAME,LNAME,EXPER;
  DBMS_OUTPUT.PUT_LINE(FNAME|| ' '||LNAME|| ' '||EXPER);
  EXIT WHEN EMP_TEST%NOTFOUND;
 END LOOP;
 CLOSE EMP_TEST;
END;















