-- STATEMENTS ( SELECT )

-- DDL ( Data Definition Language )
-- Deals with structure of database object
-- CREATE , ALTER ,DROP , TRUNCATE



-- DML ( Data Manipulation Language )
-- deals with Data only 
-- INSERT , UPDATE ,DELETE, MERGE

-- ???????
-- COMMIT , ROLLBACK

CREATE TABLE STUDENT
(
SID NUMBER,
SNAME VARCHAR2(20),
CITY VARCHAR2(20),
GENDER VARCHAR2(1),
MARKS NUMBER(3)
) ;


SELECT * FROM STUDENT ;

INSERT INTO STUDENT(SID,SNAME,CITY,GENDER,MARKS)
VALUES(1,'Sagar','Pune','M',65) ;


INSERT INTO STUDENT VALUES(2,'Amol','Pune','M',78);

INSERT INTO STUDENT(SNAME,MARKS,SID,GENDER,CITY)
VALUES('Anita',70,3,'F','Mumbai');


SELECT * FROM STUDENT ;

INSERT INTO STUDENT(SID,SNAME,CITY,GENDER) VALUES(4,'Pooja','Mumbai','F');
INSERT INTO STUDENT(SID,SNAME,CITY,GENDER) VALUES (5,'Rahul','Chennai','M');



commit;-- CTL+S

ROLLBACK ;--CTL+Z

UPDATE STUDENT
SET MARKS = 80 
WHERE SID = 4 ;

commit;
SELECT * FROM STUDENT ;

UPDATE STUDENT
SET MARKS = 75
WHERE CITY = 'Pune' ;

DELETE FROM STUDENT 
WHERE SID = 4 ;


