--PLSQL
SET SERVEROUTPUT ON;
DECLARE
EMPNO NUMBER(20);
FNAME VARCHAR2(10);
LNAME VARCHAR2(10);
SAL NUMBER;
BEGIN
  SELECT FIRST_NAME,LAST_NAME,SALARY INTO FNAME,LNAME,SAL
  FROM EMPLOYEES
  WHERE EMPLOYEE_ID=&EMPNO;
  DBMS_OUTPUT.PUT_LINE('FIRST NAME IS  '||FNAME);
  DBMS_OUTPUT.PUT_LINE('LASTNAME IS '||LNAME);
  DBMS_OUTPUT.PUT_LINE('SALARU IS '||SAL);
END;

--==================================================
DECLARE
DEPTID VARCHAR2(20);
FNAME VARCHAR2(20);
LNAME VARCHAR2(20);
SAL NUMBER(10);
BEGIN
 SELECT FIRST_NAME,LAST_NAME,SALARY INTO FNAME,LNAME,SAL
 FROM EMPLOYEES
 WHERE DEPARTMENT_ID=&DID;
 
 DBMS_OUTPUT.PUT_LINE(FNAME);
 DBMS_OUTPUT.PUT_LINE(LNAME);
 DBMS_OUTPUT.PUT_LINE(SAL);
END;

--========================================================================
--Question 1
--CALCULATE EXPERIENCE OF CANDIDATE
--IF EXP>10 THAN GIVE HIKE 10%
--EXP BETWEEN 5 -10 THAN 15%
--EXP BETWEEN 1-5 THAN 20%
SET SERVEROUTPUT ON;
DECLARE
  EID NUMBER;
  FNAME VARCHAR2(50);
  LNAME VARCHAR2(50);
  SAL NUMBER;
  EXPP NUMBER; -- Added variable for months of experience
  SALARY NUMBER;
  SALARY1 NUMBER;
  SALARY2 NUMBER;
BEGIN
  SELECT FIRST_NAME, LAST_NAME, SALARY,
         ROUND(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)/12,2) AS EXPP
  INTO FNAME, LNAME, SAL, EXPP
  FROM EMPLOYEES
  WHERE EMPLOYEE_ID = &EID;

  DBMS_OUTPUT.PUT_LINE(FNAME || ' ' || LNAME || ' ' || SAL || ' ' || EXPP);

  -- Calculate new salaries based on experience
  SALARY := SALARY + (SALARY * 0.20);
  SALARY1 := SALARY + (SALARY * 0.15);
  SALARY2 := SALARY + (SALARY * 0.05);

  -- Use a CASE statement in the SELECT to determine NEWSAL
  SELECT FIRST_NAME, LAST_NAME, SALARY,
         CASE
           WHEN EXPP > 10 THEN SALARY
           WHEN EXPP BETWEEN 1 AND 10 THEN SALARY1
           WHEN EXPP BETWEEN 11 AND 20 THEN SALARY2
         END AS NEWSAL
  INTO FNAME, LNAME, SALARY, NEWSAL
  FROM EMPLOYEES
  WHERE EMPLOYEE_ID = &EID;

  DBMS_OUTPUT.PUT_LINE('New Salary: ' || NEWSAL);
END;


--========================================
SET SERVEROUTPUT ON;
DECLARE
  EID NUMBER;
  FNAME VARCHAR2(50);
  LNAME VARCHAR2(50);
  SAL NUMBER;
  EXPP NUMBER; -- Added variable for months of experience
  NEWSAL NUMBER;
  SALARY NUMBER;
BEGIN
  -- Provide a specific value for EMPLOYEE_ID
  EID := &EID;

  SELECT 
         ROUND(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)/12,2) AS EXPP,SALARY
  INTO EXPP,SAL
  FROM EMPLOYEES
  WHERE EMPLOYEE_ID = &EID;
  
  -- Use a CASE statement in the SELECT to determine NEWSAL
  SELECT FIRST_NAME, LAST_NAME,
         CASE
           WHEN EXPP BETWEEN 1 AND 5 THEN (SALARY * 0.20)
           WHEN EXPP BETWEEN 5 AND 10 THEN  (SALARY * 1.15)
           ELSE (SAL*(1.10))
         END AS NEWSAL
  INTO FNAME, LNAME, NEWSAL
  FROM EMPLOYEES
  WHERE EMPLOYEE_ID = &EID;

  DBMS_OUTPUT.PUT_LINE(FNAME||' '||LNAME||' New Salary: ' ||' '||SAL||' '||NEWSAL);
END;






--=====================================================================
SET SERVEROUTPUT ON
DECLARE
EID NUMBER;
FNAME VARCHAR2(20);
LNAME VARCHAR2(20);
SAL NUMBER;
BEGIN
SELECT FIRST_NAME,LAST_NAME,SALARY INTO FNAME,LNAME,SAL
FROM EMPLOYEES
WHERE EMPLOYEE_ID=&EID;
DBMS_OUTPUT.PUT_LINE(FNAME||' '||LNAME||' '||SAL);
END;


--=============================================================================
--01.COPY DDL AND DATA OF STUDENT IN STUDENT_DETAILS
SET SERVEROUTPUT ON
DECLARE
BEGIN
 EXECUTE IMMEDIATE 'CREATE TABLE STUDENT_DDL_HEMANT
 AS SELECT *FROM STUDENT
 WHERE 1=2';
 DBMS_OUTPUT.PUT_LINE('TABLE CREATED SUCCESSFULLY');
END;

DECLARE
BEGIN
 INSERT INTO STUDENT_DDL_HEMANT VALUES(6,'Tanvir ','Pune','M',80);
 INSERT INTO STUDENT_DDL_HEMANT VALUES(7,'Purvaj ','Pune','M',70);
 INSERT INTO STUDENT_DDL_HEMANT VALUES(8,'Shub ','Pune','M',90);
 INSERT INTO STUDENT_DDL_HEMANT VALUES(9,'Krishna ','Pune','M',60);
END;

DECLARE
BEGIN
 EXECUTE IMMEDIATE('DROP TABLE STUDENT');
 DBMS_OUTPUT.PUT_LINE('SOURCE TABLE DELETED');
 END;


--===================================================================

DECLARE
EID NUMBER;
FNAME VARCHAR2(20);
LNAME VARCHAR2(20);
SAL NUMBER;
BEGIN
 SELECT FIRST_NAME,LAST_NAME,SALARY INTO FNAME ,LNAME,SAL
 FROM EMPLOYEES
 WHERE EMPLOYEE_ID=&EID;
DBMS_OUTPUT.PUT_LINE('FIRST NAME IS --------->'||FNAME);
DBMS_OUTPUT.PUT_LINE('LAST NAME IS ---------->'||LNAME);
DBMS_OUTPUT.PUT_LINE('SALARY IS-------------->'||SAL);
END;
--============================================================
--01.FIND EXPERIENCE OF EMPLOYEE
 --IF EXP >10 GIVE 5% HIKE
 --IF EXP BETWEEN 5 TO 10   GIVE 15%
 --IF EXP BETWEEN 1 TO 5 GIVE 20%
 
 
DECLARE
EID NUMBER;
FNAME VARCHAR2(20);
LNAME VARCHAR2(20);
SAL NUMBER;
EXPP NUMBER;
BEGIN
 SELECT FIRST_NAME,LAST_NAME,SALARY,
 ROUND(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)/12,2)  INTO FNAME,LNAME,SAL ,EXPP
 FROM EMPLOYEES
 WHERE EMPLOYEE_ID=&EID;
 DBMS_OUTPUT.PUT_LINE(FNAME||' '||LNAME||' '||SAL||' '||EXPP);
END;



SET SERVEROUTPUT ON
DECLARE
FNAME VARCHAR2(20);
LNAME VARCHAR2(20);
T_EXP NUMBER;
NEW_SAL NUMBER;
SAL NUMBER;
BEGIN
SELECT ROUND(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)/12) AS TOTAL_EXP,SALARY INTO T_EXP,SAL
FROM EMPLOYEES
WHERE EMPLOYEE_ID = &EID;

SELECT FIRST_NAME ,LAST_NAME,
CASE 
WHEN T_EXP BETWEEN 1 AND 5 THEN (SAL*(1.20))
WHEN T_EXP BETWEEN 5 AND 10 THEN (SAL*(1.15)) 
ELSE (SAL*(1.10)) END AS NEW_SAL INTO FNAME,LNAME,NEW_SAL
FROM EMPLOYEES
WHERE EMPLOYEE_ID = &EID;

DBMS_OUTPUT.PUT_LINE(FNAME||' '||LNAME||' '||T_EXP||' '||SAL||' '||NEW_SAL);
END;



--=============================================================

DECLARE
EID NUMBER;
T_EXP NUMBER;
--NEW_SAL NUMBER;
FNAME VARCHAR2(20);
LNAME VARCHAR2(20);
FINAL_SAL NUMBER;
SAL NUMBER;
BEGIN
 SELECT SALARY, ROUND(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)/12,2) AS TOTAL_EXPERIENCE INTO SAL,T_EXP
 FROM EMPLOYEES
 WHERE EMPLOYEE_ID=&EID;
 
 SELECT FIRST_NAME,LAST_NAME,
  CASE
   WHEN T_EXP BETWEEN 1 AND 5 THEN (SAL*(1.20))
   WHEN T_EXP BETWEEN 5 AND 10 THEN (SAL*(1.15))
   ELSE (SAL*(1.10)) END AS NEW_SAL INTO FNAME,LNAME,FINAL_SAL
  FROM EMPLOYEES
  WHERE EMPLOYEE_ID=&EID;
  DBMS_OUTPUT.PUT_LINE(FNAME||' '||LNAME||' '||SAL||' '||T_EXP||' '||FINAL_SAL);
END;

