SELECT *
FROM EMPLOYEES;

SELECT *FROM(
SELECT FIRST_NAME,LENGTH(FIRST_NAME) AS MAXI
FROM EMPLOYEES
ORDER BY MAXI DESC
)WHERE ROWNUM<=1;

SELECT LEFT(FIRST_NAME,2)
FROM EMPLOYEES;

SELECT *FROM(
SELECT 
D.DEPARTMENT_NAME,
COUNT(E.EMPLOYEE_ID) AS COUNT
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON (E.DEPARTMENT_ID=D.DEPARTMENT_ID)
GROUP BY D.DEPARTMENT_NAME
ORDER BY COUNT DESC
)WHERE ROWNUM<2;


SELECT *FROM (
SELECT 
FIRST_NAME,
MAX(SALARY) AS MAXIMUM
FROM EMPLOYEES
WHERE SALARY<(SELECT MAX(SALARY) AS MAXI
              FROM EMPLOYEES)
GROUP BY FIRST_NAME
ORDER BY MAXIMUM DESC
)WHERE ROWNUM<2;              


SELECT *
FROM STORE;

