SELECT *
FROM STUDENT;               --  SOURCE TABLE   

INSERT INTO STUDENT
VALUES (6,'Rakesh','Pune','M',87);
INSERT INTO STUDENT
VALUES (7,'Chandan','Bangalore','M',38);


UPDATE STUDENT 
SET MARKS=50
WHERE SID=5;

MERGE INTO STUDENT_TRG T       -- TARGET TABLE
USING STUDENT S               -- SOURCE TABLE
ON (T.SID = S.SID)            -- CONDITION
WHEN MATCHED THEN
UPDATE
SET   T.STUD_NAME = S.STUD_NAME,
      T.CITY = S.CITY,
      T.GENDER = S.GENDER,
      T.MARKS = S.MARKS
WHEN NOT MATCHED THEN
  INSERT (SID, STUD_NAME, CITY, GENDER, MARKS)
  VALUES (S.SID, S.STUD_NAME, S.CITY, S.GENDER, S.MARKS);


















--WRITE A QUERY TO TAKE BACKUP OF EXISTING TABLE.?
CREATE TABLE STUDENT_BKP
AS
SELECT * FROM STUDENT;


--WRITE A QUERY TO COPY STRUCTURE OF ONE TABLE TO ANOTHER TABLE
CREATE TABLE STUDENT_BKP_STRU
AS
SELECT *FROM STUDENT
WHERE 1=2;


--WRITE A QUERY TO LIST OUT DUPLICATE RECORDS FROM TABLE
SELECT SID,STUD_NAME,COUNT(*) AS CNT
FROM STUDENT
GROUP BY SID,STUD_NAME
HAVING COUNT(*) >1;

SELECT FIRST_NAME,COUNT(*) AS CNT
FROM EMPLOYEES
GROUP BY FIRST_NAME
HAVING COUNT(*)>1;

COMMIT;

