CREATE OR REPLACE PROCEDURE PR_NAME 
AS
 VARIABLE
 
BEGIN 
 PROCEDURE BODY -ALL LOGIC
END; 

---------------------------------------------------------------
SET SERVEROUTPUT ON
CREATE OR REPLACE PROCEDURE EMP_LOCATION(DID NUMBER) 
IS
ZERO_DID EXCEPTION;
 CURSOR EMP_DETAILS 
 IS
 SELECT
 E.FIRST_NAME,
 E.LAST_NAME,
 D.DEPARTMENT_NAME,
 L.CITY,
 L.POSTAL_CODE
 FROM EMPLOYEES E JOIN DEPARTMENTS D
 ON(E.DEPARTMENT_ID=D.DEPARTMENT_ID)
 JOIN LOCATIONS L 
 ON(D.LOCATION_ID=L.LOCATION_ID)
 WHERE E.DEPARTMENT_ID=DID;
 
 IF DID=0 THEN
 RAISE ZERO_DID;


 BEGIN
  FOR I IN EMP_DETAILS
  LOOP
   DBMS_OUTPUT.PUT_LINE(I.FIRST_NAME||' '||I.LAST_NAME||' '||I.CITY);
  END LOOP;
  EXCEPTION
  WHEN ZERO_DID THEN
   DBMS_OUTPUT.PUT_LINE('You entered zero');
 END;
 
 
 EXECUTE EMP_LOCATION(30);
 
 
 
 
 --==============================================
 --==============================================
SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE EMP_LOCATION(DID NUMBER) 
IS
ZERO_DID EXCEPTION;
BEGIN
  IF DID = 0 THEN
    RAISE ZERO_DID;
     ELSE
    FOR I IN (SELECT
                 E.FIRST_NAME,
                 E.LAST_NAME,
                 D.DEPARTMENT_NAME,
                 L.CITY,
                 L.POSTAL_CODE
               FROM EMPLOYEES E 
               JOIN DEPARTMENTS D ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
               JOIN LOCATIONS L ON (D.LOCATION_ID = L.LOCATION_ID)
               WHERE E.DEPARTMENT_ID = DID);
    LOOP
      DBMS_OUTPUT.PUT_LINE(I.FIRST_NAME || ' ' || I.LAST_NAME || ' ' || I.CITY);
    END LOOP;
  END IF;

EXCEPTION
  WHEN ZERO_DID THEN
  DBMS_OUTPUT.PUT_LINE('You entered zero');
END;

