--SEQUENCE--

CREATE TABLE MOBILE(
 MOBILE_ID NUMBER(5) CONSTRAINT M_PK PRIMARY KEY,
 BRAND VARCHAR2(10),
 PRICE NUMBER(10) CONSTRAINT M_UK UNIQUE ,CONSTRAINT CH_M CHECK(PRICE>5000)
);

CREATE SEQUENCE SEQ_MOB
INCREMENT BY 1
START WITH 100
MINVALUE 100
MAXVALUE 1000
NOCYCLE
CACHE 2
;

SELECT *
FROM MOBILE;

INSERT INTO MOBILE VALUES(SEQ_MOB.NEXTVAL,'Apple',55000);
INSERT INTO MOBILE VALUES(SEQ_MOB.NEXTVAL,'Samsung',85000);
INSERT INTO MOBILE VALUES(SEQ_MOB.NEXTVAL,'Vivo',54000);

