-- 01.What are set operators?
--Ans.The set operators are 
--    UNION
--    UNION ALL
--    INTERSECT
--    MINUS

SELECT COUNT(EMPLOYEE_ID) ,DEPARTMENT_ID
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING COUNT(EMPLOYEE_ID)>15;



SELECT DEPARTMENT_ID FROM EMPLOYEES
UNION
SELECT DEPARTMENT_ID FROM DEPARTMENTS;




SELECT DEPARTMENT_ID FROM EMPLOYEES
UNION ALL
SELECT DEPARTMENT_ID FROM EMPLOYEES;





SELECT DEPARTMENT_ID,JOB_ID FROM EMPLOYEES
INTERSECT
SELECT DEPARTMENT_ID,JOB_ID FROM EMPLOYEES;