SELECT *
FROM EMPLOYEES;

--01.WRITE Q QUERY TO FIND CITY WISE,DEPARTMENT NAME WISE COUNT OF EMPLOYEES
--DISPLAY ONLY THOSE RECORDS WHOSE COUNT >150
SELECT 
L.CITY,
D.DEPARTMENT_NAME,
COUNT(E.EMPLOYEE_ID) AS CNT
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON (E.DEPARTMENT_ID=D.DEPARTMENT_ID)
JOIN LOCATIONS L
ON(D.LOCATION_ID=L.LOCATION_ID)
GROUP BY L.CITY,D.DEPARTMENT_NAME
HAVING COUNT(E.EMPLOYEE_ID)>150;

--07.WRITE A QUERY TO DISPLAY EACH DEPARTMENT_NAME,,NUMBER OF EMP AND AVG SALARY
--FOR ALL EMP IN DEPARTMENT AND ROUND THE SAL UPTO 2 DECIMAL
SELECT 
D.DEPARTMENT_NAME,
COUNT(E.EMPLOYEE_ID) AS CNT,
ROUND(AVG(SALARY),2) AS AVERAGE_SAL
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON(E.DEPARTMENT_ID=D.DEPARTMENT_ID)
GROUP BY D.DEPARTMENT_NAME;

--10.WRITE A QUERY TO SHOW DEPARTMENT_NAME CITY WISE COUNT OF EMPLOYEE AND IN 
--OUTPUT DISPLAY ONLY THOSE CITIES WHERE MORE THAN 10 EMPLOYEES ARE WORKING
SELECT 
D.department_name,
L.city, 
COUNT(employee_id) AS employee_count
FROM departments D JOIN employees E 
ON (E.department_id = D.department_id)
JOIN LOCATIONS L 
ON(D.LOCATION_ID=L.LOCATION_ID)
GROUP BY D.department_name, L.city
HAVING COUNT(E.employee_id) > 1;





SELECT 
D.DEPARTMENT_NAME,
L.CITY,
COUNT(EMPLOYEE_ID) AS CNT
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON(E.DEPARTMENT_ID=D.DEPARTMENT_ID)
JOIN LOCATIONS L
ON(D.LOCATION_ID=L.LOCATION_ID)
GROUP BY  D.DEPARTMENT_NAME, L.CITY
HAVING COUNT(E.EMPLOYEE_ID)>10;







--01.WRITE Q QUERY TO FIND CITY WISE,DEPARTMENT NAME WISE COUNT OF EMPLOYEES
--DISPLAY ONLY THOSE RECORDS WHOSE COUNT >150
SELECT 
L.CITY,
D.DEPARTMENT_NAME,
COUNT(E.EMPLOYEE_ID) AS CNT
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON (E.DEPARTMENT_ID=D.DEPARTMENT_ID)
JOIN LOCATIONS L 
ON(D.LOCATION_ID=L.LOCATION_ID)
GROUP BY L.CITY,D.DEPARTMENT_NAME
HAVING COUNT(E.EMPLOYEE_ID)>5;


--07.WRITE A QUERY TO DISPLAY EACH DEPARTMENT_NAME,,NUMBER OF EMP AND AVG SALARY
--FOR ALL EMP IN DEPARTMENT AND ROUND THE SAL UPTO 2 DECIMAL
SELECT 
D.DEPARTMENT_NAME,
COUNT(E.EMPLOYEE_ID) AS CNT,
ROUND(AVG(E.SALARY),2) AS AVGSAL
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON(E.DEPARTMENT_ID=D.DEPARTMENT_ID)
GROUP BY D.DEPARTMENT_NAME
ORDER BY AVGSAL DESC;


--10.WRITE A QUERY TO SHOW DEPARTMENT_NAME CITY WISE COUNT OF EMPLOYEE AND IN 
--OUTPUT DISPLAY ONLY THOSE CITIES WHERE MORE THAN 10 EMPLOYEES ARE WORKING
SELECT 
D.DEPARTMENT_NAME,
COUNT(E.EMPLOYEE_ID) AS CNT,
L.CITY
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON(E.DEPARTMENT_ID=D.DEPARTMENT_ID)
JOIN LOCATIONS L
ON(D.LOCATION_ID=L.LOCATION_ID)
GROUP BY D.DEPARTMENT_NAME,L.CITY
HAVING COUNT(E.EMPLOYEE_ID)>10;

--=====================REPEAT1===========================
--01.WRITE Q QUERY TO FIND CITY WISE,DEPARTMENT NAME WISE COUNT OF EMPLOYEES
--DISPLAY ONLY THOSE RECORDS WHOSE COUNT >150.
SELECT 
L.CITY,
D.DEPARTMENT_NAME,
COUNT(E.EMPLOYEE_ID) AS CNT
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON(E.DEPARTMENT_ID=D.DEPARTMENT_ID)
JOIN LOCATIONS L 
ON(D.LOCATION_ID=L.LOCATION_ID)
GROUP BY D.DEPARTMENT_NAME,L.CITY
HAVING COUNT(E.EMPLOYEE_ID)>10;

--02.WRITE A QUERY TO DISPLAY EMPLOYEE ID AND COUNT OF CHANGE IN THEIR 
--JOBS AS PER YEAR. 
SELECT EMPLOYEE_ID,TO_CHAR(HIRE_DATE,'YYYY') AS HIRE_YEAR,
COUNT(DISTINCT JOB_ID) AS JOB_CHANGES
FROM EMPLOYEES
GROUP BY EMPLOYEE_ID,TO_CHAR(HIRE_DATE,'YYYY')
ORDER BY EMPLOYEE_ID ,HIRE_YEAR;

--03.WRITE A QUERY TO SOW TOP 3 SALARIES DEPARTMENT WISE
SELECT *FROM(
SELECT 
D.DEPARTMENT_NAME,E.FIRST_NAME,E.LAST_NAME,E.SALARY,
DENSE_RANK() OVER( ORDER BY SALARY DESC) AS DEN
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON(E.DEPARTMENT_ID=D.DEPARTMENT_ID)
)WHERE DEN<4;


WITH TEMP1 AS
(SELECT 
D.DEPARTMENT_NAME,E.FIRST_NAME,E.LAST_NAME,E.SALARY,
DENSE_RANK() OVER( ORDER BY SALARY DESC) AS DEN
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON(E.DEPARTMENT_ID=D.DEPARTMENT_ID)
)
SELECT *
FROM TEMP1
WHERE DEN<4;

--===================================================================================
DECLARE
TABLE1 VARCHAR2(32767);
TABLE2 VARCHAR2(32767);
BEGIN
TABLE1:= q'[CREATE TABLE STUDENT1 AS
                 (SELECT *FROM STUDENT)]';
EXECUTE IMMEDIATE TABLE1;
TABLE2:=q'[DROP TABLE STUDENT]';
END;




---=========================3rd March--=======================================
--01.WRITE Q QUERY TO FIND CITY WISE,DEPARTMENT NAME WISE COUNT OF EMPLOYEES
--DISPLAY ONLY THOSE RECORDS WHOSE COUNT >150
SELECT 
L.CITY,
D.DEPARTMENT_NAME,
COUNT(E.EMPLOYEE_ID) AS CNT
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON(E.DEPARTMENT_ID=D.DEPARTMENT_ID)
JOIN LOCATIONS L
ON(D.LOCATION_ID=L.LOCATION_ID)
GROUP BY L.CITY,D.DEPARTMENT_NAME
HAVING COUNT(E.EMPLOYEE_ID)>5;

--07.WRITE A QUERY TO DISPLAY EACH DEPARTMENT_NAME,,NUMBER OF EMP AND AVG SALARY
--FOR ALL EMP IN DEPARTMENT AND ROUND THE SAL UPTO 2 DECIMAL

SELECT 
D.DEPARTMENT_NAME,
COUNT(E.EMPLOYEE_ID) AS CNT,
ROUND(AVG(E.SALARY),2) AS AVERAGE_SALARY
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON(E.DEPARTMENT_ID=D.DEPARTMENT_ID)
GROUP BY D.DEPARTMENT_NAME;

--10.WRITE A QUERY TO SHOW DEPARTMENT_NAME CITY WISE COUNT OF EMPLOYEE AND IN 
--OUTPUT DISPLAY ONLY THOSE CITIES WHERE MORE THAN 10 EMPLOYEES ARE WORKING
SELECT 
D.DEPARTMENT_NAME,
L.CITY,
COUNT(E.EMPLOYEE_ID) AS CNT
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON(E.DEPARTMENT_ID=D.DEPARTMENT_ID)
JOIN LOCATIONS L
ON(D.LOCATION_ID=L.LOCATION_ID)
GROUP BY D.DEPARTMENT_NAME,L.CITY
HAVING COUNT(E.EMPLOYEE_ID)>5;










