SELECT *
FROM EMPLOYEES;

--01.WRITE Q QUERY TO FIND CITY WISE,DEPARTMENT NAME WISE COUNT OF EMPLOYEES
--DISPLAY ONLY THOSE RECORDS WHOSE COUNT >150
SELECT 
L.CITY,
D.DEPARTMENT_NAME,
COUNT(E.EMPLOYEE_ID) AS CNT
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON (E.DEPARTMENT_ID=D.DEPARTMENT_ID)
JOIN LOCATIONS L
ON(D.LOCATION_ID=L.LOCATION_ID)
GROUP BY L.CITY,D.DEPARTMENT_NAME
HAVING COUNT(E.EMPLOYEE_ID)>150;

--07.WRITE A QUERY TO DISPLAY EACH DEPARTMENT_NAME,,NUMBER OF EMP AND AVG SALARY
--FOR ALL EMP IN DEPARTMENT AND ROUND THE SAL UPTO 2 DECIMAL
SELECT 
D.DEPARTMENT_NAME,
COUNT(E.EMPLOYEE_ID) AS CNT,
ROUND(AVG(SALARY),2) AS AVERAGE_SAL
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON(E.DEPARTMENT_ID=D.DEPARTMENT_ID)
GROUP BY D.DEPARTMENT_NAME;

--10.WRITE A QUERY TO SHOW DEPARTMENT_NAME CITY WISE COUNT OF EMPLOYEE AND IN 
--OUTPUT DISPLAY ONLY THOSE CITIES WHERE MORE THAN 10 EMPLOYEES ARE WORKING
SELECT *FROM(
SELECT 
D.DEPARTMENT_NAME,L.CITY,
COUNT(E.EMPLOYEE_ID) OVER(PARTITION BY L.CITY ORDER BY E.EMPLOYEE_ID) AS CNT
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON(E.DEPARTMENT_ID=D.DEPARTMENT_ID)
JOIN LOCATIONS L
ON(D.LOCATION_ID=L.LOCATION_ID)
)WHERE CNT>10;


SELECT 
D.department_name,
L.city, 
COUNT(employee_id) AS employee_count
FROM departments D JOIN employees E 
ON (E.department_id = D.department_id)
JOIN LOCATIONS L 
ON(D.LOCATION_ID=L.LOCATION_ID)
GROUP BY D.department_name, L.city
HAVING COUNT(E.employee_id) > 1;







SELECT 
D.DEPARTMENT_NAME,
L.CITY,
COUNT(EMPLOYEE_ID) AS CNT
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON(E.DEPARTMENT_ID=D.DEPARTMENT_ID)
JOIN LOCATIONS L
ON(D.LOCATION_ID=L.LOCATION_ID)
GROUP BY  D.DEPARTMENT_NAME, L.CITY
HAVING COUNT(E.EMPLOYEE_ID)>10;

