CREATE TABLE PERSON(
 NAME VARCHAR2(10),
 AGE NUMBER(2)
);

SELECT *
FROM PERSON;

INSERT INTO PERSON
VALUES('Tanvir',24);
INSERT INTO PERSON
VALUES('Aniket',24);


-- 01. WHAT IS TRUNCATE?
--ANS.TRUNCATE WILL MAKE MAKE THE TABLE EMPTY
--    TABLE STRUCTURE IS PRESERVED
--    ITS FASTER THAN DELETE
--    Autoincrement will be reset
TRUNCATE TABLE PERSON;


-- 02. WHAT IS DELETE?
--ANS.DELETE WILL MAKE MAKE THE TABLE EMPTY
--    TABLE STRUCTURE IS PRESERVED
--    ITS SLOWER THAN TRUNCATE
--    Autoincrement will NOT be reset
DELETE FROM  PERSON;



-- 02. WHAT IS DROP?
--ANS.DROP WILL REMOVE  THE TABLE FROM DATABASE
--    Autoincrement will NOT be reset
DROP TABLE  PERSON;

