--THE BEST WAY TO UNDERSTAND THE WINDOW FUNCTION IS BY FIRST GOING THROUGH AN
--AGGREGATE FUNCTION
SELECT *
FROM EMPLOYEE;

--EXTRACT THE MAX SALARY  IN EACH DEPARTMENT
SELECT D.DEPARTMENT_NAME,
MAX(E.SALARY)
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON (E.DEPARTMENT_ID=D.DEPARTMENT_ID)
GROUP BY D.DEPARTMENT_NAME;





--FETCH THE TOP 3 EMPLOYEE IN EACH DEPARTMENT EARNING THE MAX SALARY
SELECT *FROM(
SELECT E.FIRST_NAME,
D.DEPARTMENT_NAME,E.SALARY,
RANK() OVER(PARTITION BY D.DEPARTMENT_NAME ORDER BY E.SALARY DESC) AS RNK
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON (E.DEPARTMENT_ID=D.DEPARTMENT_ID)
)WHERE RNK<=3;

--HOW MANY EMPLOYEES WORKING IN ACCOUNTING;
SELECT D.DEPARTMENT_NAME,COUNT(E.EMPLOYEE_ID) AS CNT
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON (E.DEPARTMENT_ID=D.DEPARTMENT_ID)
WHERE UPPER(D.DEPARTMENT_NAME)='ACCOUNTING'
GROUP BY D.DEPARTMENT_NAME;





--WHAT IS LEAD() AND LAG()?
SELECT E.EMPLOYEE_ID,D.DEPARTMENT_NAME,E.SALARY,
LAG(E.SALARY) OVER(PARTITION BY D.DEPARTMENT_NAME ORDER BY E.EMPLOYEE_ID) AS PREVI_EMP_SAL
FROM EMPLOYEES E JOIN DEPARTMENTS D

ON (E.DEPARTMENT_ID=D.DEPARTMENT_ID);


