--FETCH EMPLOYEES WHO EARN MORE 2 times THAN AVERAGE SALARY
WITH DEPT_TOTAL_SAL AS
(
SELECT DEPARTMENT_ID , SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID ) ,

DEPT_AVG_SAL AS
(
SELECT DEPARTMENT_ID , TRUNC(AVG(SALARY)) AS AVG_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID)

SELECT 
t1.DEPARTMENT_ID , 
d.DEPARTMENT_NAME,
t1.TOTAL_SALARY , 
t2.AVG_SALARY
FROM DEPT_TOTAL_SAL t1 JOIN DEPT_AVG_SAL t2 
ON (t1.DEPARTMENT_ID = t2.DEPARTMENT_ID
AND t1.TOTAL_SALARY > (2*t2.AVG_SALARY) ) 
JOIN DEPARTMENTS d 
ON( t1.DEPARTMENT_ID = d.DEPARTMENT_ID);
