--FETCH EMPLOYEES WHO EARN  2 times THAN AVERAGE SALARY
WITH DEPT_TOTAL_SAL AS
(
SELECT DEPARTMENT_ID , SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID ) ,

DEPT_AVG_SAL AS
(
SELECT DEPARTMENT_ID , TRUNC(AVG(SALARY)) AS AVG_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID)

SELECT 
t1.DEPARTMENT_ID , 
d.DEPARTMENT_NAME,
t1.TOTAL_SALARY , 
t2.AVG_SALARY
FROM DEPT_TOTAL_SAL t1 JOIN DEPT_AVG_SAL t2 
ON (t1.DEPARTMENT_ID = t2.DEPARTMENT_ID
AND t1.TOTAL_SALARY > (2*t2.AVG_SALARY) ) 
JOIN DEPARTMENTS d 
ON( t1.DEPARTMENT_ID = d.DEPARTMENT_ID);


--FETCH EMPLOYEES WHO EARN MORE THAN  2 times THAN AVERAGE SALARY
WITH DEPT_TOTAL_SALARY 
AS
( SELECT DEPARTMENT_ID,SUM(SALARY) AS TOTAL_SALARY
  FROM EMPLOYEES
  GROUP BY DEPARTMENT_ID
),
 DEPT_AVG_SAL
 AS
 (SELECT DEPARTMENT_ID,TRUNC(AVG(SALARY)) AS AVG_SALARY 
  FROM EMPLOYEES
  GROUP BY DEPARTMENT_ID
 )
SELECT 
T1.DEPARTMENT_ID,
D.DEPARTMENT_NAME,
T2.AVG_SALARY,
T1.TOTAL_SALARY
FROM DEPT_TOTAL_SALARY T1 JOIN DEPT_AVG_SAL T2
ON (T1.DEPARTMENT_ID=T2.DEPARTMENT_ID)
AND 
(T1.TOTAL_SALARY>(2*T2.AVG_SALARY ))
JOIN DEPARTMENTS D
ON (D.DEPARTMENT_ID=T1.DEPARTMENT_ID);






--WAQD- DEPARTMENT IN WHICH SUM OF SALARY IS GREATER THAN DOUBLE OF 
--AVG SALARY OF THEIR CORRESPONDING DEPARTMENT--
WITH  DEPT_SUM_SALARY
AS
( SELECT DEPARTMENT_ID,SUM(SALARY) AS TOTAL_SUM_SALARY
  FROM EMPLOYEES 
  GROUP BY DEPARTMENT_ID
),
 DEPT_AVG_SALARY AS
 (SELECT DEPARTMENT_ID,TRUNC(AVG(SALARY)) AS AVG_SALARY
  FROM EMPLOYEES
  GROUP BY DEPARTMENT_ID
 )
 
 SELECT T1.DEPARTMENT_ID,D.DEPARTMENT_NAME,T1.TOTAL_SUM_SALARY,T2.AVG_SALARY
 FROM DEPT_SUM_SALARY T1 JOIN DEPT_AVG_SALARY T2
 ON (T1.DEPARTMENT_ID=T2.DEPARTMENT_ID)
 AND(T1.TOTAL_SUM_SALARY>(2*T2.AVG_SALARY))
 JOIN DEPARTMENTS D
 ON (T1.DEPARTMENT_ID=D.DEPARTMENT_ID);

 


SELECT DEPARTMENT_ID,COUNT(*) AS CNT
FROM EMPLOYEES
WHERE TO_CHAR(HIRE_DATE,'YYYY') = TO_CHAR(SYSDATE,'YYYY') - 18
GROUP BY DEPARTMENT_ID,TO_CHAR(HIRE_DATE,'YYYY');

SELECT DEPARTMENT_ID,COUNT(*) AS CNT
FROM EMPLOYEES
WHERE TO_CHAR(HIRE_DATE,'YYYY')=2003
GROUP BY DEPARTMENT_ID;




WITH DEPT_SUM_SAL
AS
(SELECT DEPARTMENT_ID,SUM(SALARY) AS TOTAL_SUM
 FROM EMPLOYEES
 GROUP BY DEPARTMENT_ID),

DEPT_AVG_SALARY
AS
(SELECT DEPARTMENT_ID,TRUNC(AVG(SALARY)) AS DEPT_AVG_SALARY
 FROM EMPLOYEES 
 GROUP BY DEPARTMENT_ID)
 
SELECT T1.DEPARTMENT_ID,D.DEPARTMENT_NAME,T1.TOTAL_SUM,T2.DEPT_AVG_SALARY
FROM DEPT_SUM_SAL T1 JOIN DEPT_AVG_SALARY T2
ON (T1.DEPARTMENT_ID=T2.DEPARTMENT_ID)
AND(T1.TOTAL_SUM>(2*T2.DEPT_AVG_SALARY))
JOIN DEPARTMENTS D
ON (T1.DEPARTMENT_ID=D.DEPARTMENT_ID);


 








